CREATE TABLE IF NOT EXISTS `MaliciousScans` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `url` VARCHAR(512) NOT NULL,
    `status` VARCHAR(20) NOT NULL,
    `category` VARCHAR(50) NOT NULL,
    `domain` VARCHAR(255) NOT NULL,
    `domain_age` DATETIME NULL,
    `is_api` TINYINT(1) DEFAULT 1,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;